In [135]:
#pip install polars
#pip install bottleneck
import os
import pandas as pd
import numpy as np
import polars as pl
import bottleneck as bn
df=pl.read_csv('/content/drive/MyDrive/Colab/train.csv')
dfpd=pd.read_csv('/content/drive/MyDrive/Colab/train.csv')
housing=pd.read_csv('/content/drive/MyDrive/Colab/Housing.csv')

In [136]:
df.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

In [137]:
df.get_column('Pclass').value_counts()

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 2      ┆ 184   │
│ 3      ┆ 491   │
│ 1      ┆ 216   │
└────────┴───────┘

In [138]:
df.null_count()

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [139]:
df[['Age', 'Pclass']].mean()

shape: (1, 2)
┌───────────┬──────────┐
│ Age       ┆ Pclass   │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ 29.699118 ┆ 2.308642 │
└───────────┴──────────┘

In [140]:
df.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [141]:
df.filter(pl.col('Age')>44)

shape: (115, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.    ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J        ┆   ┆            ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.   ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth        ┆   ┆            ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.    ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D          ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…        ┆   ┆            ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.     ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H         ┆   ┆            ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.     ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper    ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…             ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter  ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│             ┆          ┆        ┆ Denis            ┆   ┆            ┆         ┆       ┆          │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs.      ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│             ┆          ┆        ┆ Frederick Joel   ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Ma…             ┆   ┆            ┆         ┆       ┆          │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs.   ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│             ┆          ┆        ┆ Richard Leonard… ┆   ┆            ┆         ┆       ┆          │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│             ┆          ┆        ┆ Mr. Victor       ┆   ┆            ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.     ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily  ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…               ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [142]:
df.group_by('Sex').agg(pl.col('Survived').sum())

shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Survived │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ female ┆ 233      │
│ male   ┆ 109      │
└────────┴──────────┘

In [143]:
bn.nanmean(dfpd['Age'])

29.69911764705882

In [144]:
bn.nanstd(dfpd['Age'])

14.516321150817317

In [145]:
new=df.with_columns([(pl.col('Fare') * 1.3)
.alias('Fare_new')])
new.head(5)

shape: (5, 13)
┌─────────────┬──────────┬────────┬────────────────────┬───┬─────────┬───────┬──────────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name               ┆ … ┆ Fare    ┆ Cabin ┆ Embarked ┆ Fare_new │
│ ---         ┆ ---      ┆ ---    ┆ ---                ┆   ┆ ---     ┆ ---   ┆ ---      ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                ┆   ┆ f64     ┆ str   ┆ str      ┆ f64      │
╞═════════════╪══════════╪════════╪════════════════════╪═══╪═════════╪═══════╪══════════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen   ┆ … ┆ 7.25    ┆ null  ┆ S        ┆ 9.425    │
│             ┆          ┆        ┆ Harris             ┆   ┆         ┆       ┆          ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs. John ┆ … ┆ 71.2833 ┆ C85   ┆ C        ┆ 92.66829 │
│             ┆          ┆        ┆ Bradley (Fl…       ┆   ┆         ┆       ┆          ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.   ┆ … ┆ 7.925   ┆ null  ┆ S        ┆ 10.3025  │
│             ┆          ┆        ┆ Laina              ┆   ┆         ┆       ┆          ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.     ┆ … ┆ 53.1    ┆ C123  ┆ S        ┆ 69.03    │
│             ┆          ┆        ┆ Jacques Heath (…   ┆   ┆         ┆       ┆          ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr. William ┆ … ┆ 8.05    ┆ null  ┆ S        ┆ 10.465   │
│             ┆          ┆        ┆ Henry              ┆   ┆         ┆       ┆          ┆          │
└─────────────┴──────────┴────────┴────────────────────┴───┴─────────┴───────┴──────────┴──────────┘

In [146]:
housing.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [147]:
#221.9kb
housing.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 221.9 KB

In [148]:
housing['price'].astype(np.int8).info(memory_usage="deep")#677B - оптимальный
housing['price'].astype('category').info(memory_usage="deep")#11kB
housing['price'].astype(np.int64).info(memory_usage="deep")#4.4kb
housing['price'].astype(bytes).info(memory_usage="deep")#11.3kB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: price
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: price
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 11.0 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: price
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: price
Non-Null Count  Dtype
--------------  -----
545 non-null    |S21
dtypes: object(1)
memory usage: 11.3 KB

In [149]:
housing['area'].astype(np.int8).info(memory_usage="deep")#677b - оптимальный
housing['area'].astype('category').info(memory_usage="deep")#11.5kB
housing['area'].astype(np.int64).info(memory_usage="deep")#4.4kB
housing['area'].astype(bytes).info(memory_usage='deep')#11.3KB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: area
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: area
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 11.5 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: area
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: area
Non-Null Count  Dtype
--------------  -----
545 non-null    |S21
dtypes: object(1)
memory usage: 11.3 KB

In [150]:
housing['bedrooms'].astype(np.int8).info(memory_usage="deep")#677B - оптимальный
housing['bedrooms'].astype('category').info(memory_usage="deep")#897B
housing['bedrooms'].astype(np.int64).info(memory_usage="deep")#4.4kB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bedrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bedrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 897.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bedrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB

In [151]:
housing['bathrooms'].astype(np.int8).info(memory_usage="deep")#677B - оптимальный
housing['bathrooms'].astype('category').info(memory_usage="deep")#881B
housing['bathrooms'].astype(np.int64).info(memory_usage="deep")#4.4kB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bathrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bathrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 881.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: bathrooms
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB

In [152]:
housing['stories'].astype(np.int8).info(memory_usage="deep")#677B - оптимальный
housing['stories'].astype('category').info(memory_usage="deep")#881B
housing['stories'].astype(np.int64).info(memory_usage="deep")#4.4kB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: stories
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: stories
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 881.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: stories
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB

In [153]:
housing['mainroad'].astype(object).info(memory_usage="deep")#27kB
housing['mainroad'].astype('category').info(memory_usage="deep")#888B
housing['mainroad'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: mainroad
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.7 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: mainroad
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: mainroad
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [154]:
housing['guestroom'].astype(object).info(memory_usage="deep")#27kB
housing['guestroom'].astype('category').info(memory_usage="deep")#888B
housing['guestroom'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: guestroom
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: guestroom
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: guestroom
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [155]:
housing['basement'].astype(object).info(memory_usage="deep")#27.5kB
housing['basement'].astype('category').info(memory_usage="deep")#888B
housing['basement'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: basement
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.5 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: basement
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: basement
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [156]:
housing['hotwaterheating'].astype(object).info(memory_usage="deep")#27kB
housing['hotwaterheating'].astype('category').info(memory_usage="deep")#888B
housing['hotwaterheating'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: hotwaterheating
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.3 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: hotwaterheating
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: hotwaterheating
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [157]:
housing['airconditioning'].astype(object).info(memory_usage="deep")#27.4kB
housing['airconditioning'].astype('category').info(memory_usage="deep")#888B
housing['airconditioning'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: airconditioning
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: airconditioning
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: airconditioning
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [158]:
housing['parking'].astype(np.int8).info(memory_usage="deep")#677B оптимальный
housing['parking'].astype('category').info(memory_usage="deep")#881B
housing['parking'].astype(np.int64).info(memory_usage="deep")#4.4KB

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: parking
Non-Null Count  Dtype
--------------  -----
545 non-null    int8
dtypes: int8(1)
memory usage: 677.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: parking
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 881.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: parking
Non-Null Count  Dtype
--------------  -----
545 non-null    int64
dtypes: int64(1)
memory usage: 4.4 KB

In [159]:
housing['prefarea'].astype(object).info(memory_usage="deep")#27.4kB
housing['prefarea'].astype('category').info(memory_usage="deep")#888B
housing['prefarea'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: prefarea
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 27.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: prefarea
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 888.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: prefarea
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [160]:
housing['furnishingstatus'].astype(object).info(memory_usage="deep")#32.5kB
housing['furnishingstatus'].astype('category').info(memory_usage="deep")#966B
housing['furnishingstatus'].astype(bool).info(memory_usage="deep")#677B оптимальный

<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: furnishingstatus
Non-Null Count  Dtype
--------------  -----
545 non-null    object
dtypes: object(1)
memory usage: 32.5 KB
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: furnishingstatus
Non-Null Count  Dtype
--------------  -----
545 non-null    category
dtypes: category(1)
memory usage: 966.0 bytes
<class 'pandas.core.series.Series'>
RangeIndex: 545 entries, 0 to 544
Series name: furnishingstatus
Non-Null Count  Dtype
--------------  -----
545 non-null    bool
dtypes: bool(1)
memory usage: 677.0 bytes

In [161]:
housing['bedrooms']=housing['bedrooms'].astype(np.int8)
housing['price']=housing['price'].astype(np.int8)
housing['area']=housing['area'].astype(np.int8)
housing['bathrooms']=housing['bathrooms'].astype(np.int8)
housing['stories']=housing['stories'].astype(np.int8)
housing['mainroad']=housing['mainroad'].astype(bool)
housing['guestroom']=housing['guestroom'].astype(bool)
housing['basement']=housing['basement'].astype(bool)
housing['hotwaterheating']=housing['hotwaterheating'].astype(bool)
housing['airconditioning']=housing['airconditioning'].astype(bool)
housing['parking']=housing['parking'].astype(np.int8)
housing['prefarea']=housing['prefarea'].astype(bool)
housing['furnishingstatus']=housing['furnishingstatus'].astype(bool)
housing.info(memory_usage='deep') #7KB - оптимизация памяти в 30 раз

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int8
 1   area              545 non-null    int8
 2   bedrooms          545 non-null    int8
 3   bathrooms         545 non-null    int8
 4   stories           545 non-null    int8
 5   mainroad          545 non-null    bool
 6   guestroom         545 non-null    bool
 7   basement          545 non-null    bool
 8   hotwaterheating   545 non-null    bool
 9   airconditioning   545 non-null    bool
 10  parking           545 non-null    int8
 11  prefarea          545 non-null    bool
 12  furnishingstatus  545 non-null    bool
dtypes: bool(7), int8(6)
memory usage: 7.0 KB